---
- name: Get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw
  when: hostvars[ansible_hostname].group_names[0] == "k8s-master"

- name: Set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"
  when: hostvars[ansible_hostname].group_names[0] == "k8s-master"

- name: Join cluster
  shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt
  when: hostvars[ansible_hostname].group_names[0] == "k8s-node"
